#!/usr/bin/perl
use strict;
use warnings;
use Dancer ':script';
use Path::Class qw(file);
use Digest::MD5 qw(md5_hex);
use DBI;
print "Taracot installation script\nDatabase configuration\n\n";
my $root = file($0)->absolute->dir;
$root =~s/\\/\//gm;
$root =~s/\/installation$//; 
push (@INC, $root.'/lib');
print "Loading Dancer config. You should see no errors there...\n";
Dancer::Config::setting('appdir', $root);
Dancer::Config::setting('confdir', $root);
Dancer::Config::load(); 
print "Connecting to the database...\n";
my $dbh;
my $DSN = 'DBI:mysql:'.config->{plugins}->{Database}->{database}.':'.config->{plugins}->{Database}->{host};
$dbh = DBI->connect($DSN, config->{plugins}->{Database}->{username}, config->{plugins}->{Database}->{password});
my $sth = $dbh->prepare("SET NAMES 'utf8'");
$sth->execute();
$sth->finish();
$sth = $dbh->prepare("SET CHARACTER SET 'utf8'");
$sth->execute();
$sth->finish();
print "Opening SQL schema...\n";
open(DATA, "taracot.sql");
my @sql = <DATA>;
close(DATA);
print "Processing SQL requests...\n";
foreach my $req (@sql) {	
	$sth = $dbh->prepare($req);
	$sth->execute();
	$sth->finish();
}
print "\nNeed to create a new administrator.\n\nPlease enter username: ";
my $username = <STDIN>;
chomp($username);
print "Please enter password: ";
my $password = <STDIN>;
chomp($password);
print "Creating new user...\n";
$sth = $dbh->prepare("INSERT INTO taracot_users SET status=2, username=".$dbh->quote($username).", password=".$dbh->quote(md5_hex(config->{salt}.$password)).", regdate=".time);
$sth->execute();
$sth->finish();
print "Disconnecting from the database...\n";
$dbh->disconnect();
$dbh = undef;
print "\nInstallation complete!\n";