appname: 'taracot'
server: '0.0.0.0'
port: '2999'
daemon: 'false'
layout: 'taracot'
layouts_available: 'taracot'
charset: 'UTF-8'
template: 'tenjin'
environment: 'development'
root_dir: 'c:/xtreme/taracot/'
data_dir: 'data'
files_dir: 'c:/xtreme/taracot/public/files/'
files_url: '/files'
modules_css_url: '/css/modules/'
session_dir: 'c:/xtreme/taracot/tmp/sessions/'
session: 'Storable'
session_name: 'taracot_session'
session_expires: '1 week'
load_modules_admin: 'users, pages, catalog, sitemap, files, settings'
load_modules_frontend: 'pages, catalog, imgbrowser, user'
load_blocks_frontend: 'menu, catalog_special, blocks'
lang_available: 'en, ru'
lang_available_long: 'English, Русский'
lang_default: 'en'
db_table_prefix: 'taracot'
salt: 'zuwrezathutebruhap6a558efane7asethe87caC44spa6upebrajaDrasares6u'
cached_settings: 'block_left, block_right'
agreement: '/agreement'
captcha_font: 'ank.ttf'
site_logo_url: /taracot/logo_white_235.png

plugins:
 Database:
  driver: 'mysql'
  database: 'taracot'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: ""
  connection_check_threshold: 10
  dbi_params:
   RaiseError: 1
   AutoCommit: 1
  on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
  log_queries: 1
 Email:
  headers:
    from: 'noreply@taracot.org'
    X-Mailer: 'Taracot CMS'
  transport:
    Sendmail:
      sendmail: 'c:/XTreme/local/usr/bin/sendmail.exe'
