appname: 'taracot'
server: '0.0.0.0'
port: '2999'
daemon: 'false'
layout: 'taracot'
layouts_available: 'taracot'
charset: 'UTF-8'
template: 'tenjin'
environment: 'development'
root_dir: 'c:/xtreme/taracot/'
data_dir: 'data'
files_dir: 'c:/xtreme/taracot/public/files/'
files_url: '/files'
modules_css_url: '/css/modules/'
session_dir: 'c:/xtreme/taracot/tmp/sessions/'
session: 'Storable'
session_name: 'taracot_session'
session_expires: '1 week'
load_modules_admin: 'users, pages, sitemap, files, billing, settings'
load_modules_frontend: 'pages, imgbrowser, user, blog, webmoney, robokassa'
load_blocks_frontend: 'menu, blocks'
lang_available: 'en, ru, de'
lang_available_long: 'English, Russian, German'
lang_default: 'en'
db_table_prefix: 'taracot'
salt: 'zuwrezathutebruhap6a558efane7asethe87caC44spa6upebrajaDrasares6u'
cached_settings: 'block_left, block_right'
agreement: '/agreement'
captcha_font: 'ank.ttf'
site_logo_url: /taracot/logo_white_235.png
upload_limit_bytes: '3145728'
billing_cpanel_plugin: 'ispmanager'

auth_facebook_app_id: ''
auth_facebook_app_secret: ''
auth_facebook_redirect_uri: 'http://sandbox.taracot.org/user/authorize/facebook/'
auth_google_client_id: ''
auth_google_client_secret: ''
auth_google_redirect_uri: 'http://sandbox.taracot.org/user/authorize/google/'
auth_yandex_client_id: ''
auth_yandex_client_secret: ''
auth_vk_client_id: ''
auth_vk_client_secret: ''
auth_vk_redirect_uri: 'http://sandbox.taracot.org/user/authorize/vk/'

plugins:
 Database:
  driver: 'mysql'
  database: 'taracot'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: ""
  connection_check_threshold: 10
  dbi_params:
   RaiseError: 1
   AutoCommit: 1
  on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
  log_queries: 1
 Email:
  headers:
    from: 'Taracot CMS <noreply@taracot.org>'
    X-Mailer: 'Taracot CMS'
  transport:
    Sendmail:
      sendmail: 'c:/Denwer/usr/bin/sendmail.exe'
